backend:
  name: github
  repo: KULLANICI_ADI/REPO_ADI
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "icerik"
    label: "Site İçeriği"
    files:
      - file: "data/content.json"
        label: "Haberler ve Ekip"
        name: "content"
        fields:
          - label: "Haberler"
            name: "haberler"
            widget: "list"
            summary: "{{fields.baslik}}"
            fields:
              - {label: "Başlık", name: "baslik", widget: "string"}
              - {label: "Açıklama", name: "aciklama", widget: "text"}
              - {label: "Tarih", name: "tarih", widget: "string"}
              - label: "Durum"
                name: "durum"
                widget: "select"
                options: ["tamamlandi", "planlaniyor"]
                default: "planlaniyor"

          - label: "Ekip"
            name: "ekip"
            widget: "list"
            summary: "{{fields.isim}}"
            fields:
              - {label: "Fotoğraf", name: "fotograf", widget: "image", required: false}
              - {label: "İsim", name: "isim", widget: "string"}
              - {label: "Unvan", name: "unvan", widget: "string"}
              - {label: "Açıklama", name: "aciklama", widget: "text"}
